{{- $secret := default (dict) .Values.web.secret -}}
{{- if and (not .Values.web.existingSecret) (gt (len $secret) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schizm.webSecretName" . }}
  labels:
    {{- include "schizm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
stringData:
  {{- range $key := keys $secret | sortAlpha }}
  {{ $key }}: {{ printf "%v" (index $secret $key) | quote }}
  {{- end }}
{{- end }}
