apiVersion: v1
kind: Service
metadata:
  name: {{ include "schizm.webName" . }}
  labels:
    {{- include "schizm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "schizm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and .Values.web.service.nodePort (or (eq .Values.web.service.type "NodePort") (eq .Values.web.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
