apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: schizm
  namespace: fleet-local
spec:
  repo: git@github.com:smysnk/schizsm.git
  clientSecretName: smysnk-com-github-ssh
  branch: main
  paths:
    - fleet
